# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: "Pieter's Totem"
on: workflow_dispatch
jobs:
  build:
    if: github.repository_owner == 'jonahgoldwastaken'
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["totem_left","totem_right"]'
      alphas: '["qwerty"]'
      extra: '["colemak"]'
      tap: '["qwerty"]'
      nav: '["vi"]'
      clipboard: '["mac"]'
      layers: '["default"]'
